apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: {docker_repository_image_path:image_tag}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          value: "{mongodb_cluster_uri}"