apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartapp
  labels:
    app: cartapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartapp
  template:
    metadata:
      labels:
        app: cartapp
    spec:
      containers:
      - name: cartapp
        image: //docker_hub_repository
        ports:
        - containerPort: 5004
        imagePullPolicy: Always
        env:
        - name: MONGO_URI
          value: "mongo_db_url"
