apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartapp
  labels:
    app: cartapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartapp
  template:
    metadata:
      labels:
        app: cartapp
    spec:
      containers:
      - name: cartapp
        image: aditiprabhu/ecommercec:v4
        ports:
        - containerPort: 5004
        imagePullPolicy: Always
        env:
        - name: MONGO_URI
          value: "mongodb+srv://arevanthsreeram:Dg4eP6YcuClsxTf9@cluster0.lgmqzy1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
